__author__ = 'Donald'

APP_CLIENT = "appClient"

appClient = {
    #name: (module, extra params, attributes)
    'clientId': (None, None, None),
    'clientSecret': (None, None, None),
    'universe': ('UniverseParser', None, None),
    'accessTokenExpiration': ('AccessTokenExpirationParser', None, None),
    'idTokenExpiration': ('IdTokenExpirationParser', None, None),
    'refreshTokenExpiration': ('RefreshTokenExpirationParser', None, None),
    'lastAuthDateUpdateCoolDownInSeconds': ('LastAuthDateUpdateCoolDownInSecondsParser', None, None),
    'loginRequiredForAccessToken': ('LoginRequiredForAccessTokenParser', None, None),
    'recaptchaDisabled': ('RecaptchaDisabledParser', None, None),
    'twoFactorAuthenticationEnabled': ('TwoFactorAuthenticationEnabledParser', None, None),
    'allowedAuthenticationSources': ('AllowedAuthenticationSourcesParser',
                                     ['defaultAuthenticationSource'], 'authenticationSource'),
    'defaultAuthenticationSource': (None, None, None),
    'allowedClientIds': ('AllowedClientIdsParser', None, 'clientId'),
    'allowedDisplays': ('AllowedDisplaysParser', 'defaultDisplay', 'displayType'),
    'allowedGrantTypes': ('AllowedGrantTypesParser', None, 'grantType'),
    'allowedRedirectUris': ('AllowedRedirectUrisParser', ['defaultRedirectUri', 'defaultRedirectUriForLogout'], 'uri'),
    'allowedMobileLoginTypes': ('AllowedMobileLoginTypesParser', None, 'mobileLoginType'),
    'allowedResponseTypes': ('AllowedResponseTypesParser', None, 'responseType'),
    'allowedRegistrationSources': ('AllowedRegistrationSourcesParser',
                                   ['defaultAuthenticationSource'], 'registrationSource'),
    'allowedScopes': ('AllowedScopesParser', ['defaultScopes'], 'scope'),
    'defaultRedirectUri': (None, None, None),
    'defaultRedirectUriForLogout': (None, None, None),
    'apiIpWhitelists': ('ApiIpWhistlistsParser', None, ['apiIpWhitelist']),
    'authorizationCodeConfig': ('AuthorizationCodeConfigParser', None, ['redirectUriCheck']),
    'authorizationCodeExpiration': ('AuthorizationCodeExpirationParser', None, None),
    'authTokenAccess': ('AuthTokenAccessParser', None, ['enabled', 'scopes']),
    'clientCertificateMappings': ('ClientCertificateMappingsParser', None, ['clientCertificateMapping']),
    'clientCredentialsConfig': ('ClientCredentialsConfigParser', ['allowedGrantTypes'], ['pidIdState']),
    'clientMigrationConfig': ('ClientMigrationConfigParser', None, ['enabled',
                                                                    'allowedMigrationStatus', 'migrationClientIds']),
    'defaultDisplay': ('DefaultDisplayParser', None, None),
    'defaultLocale': (None, None, None),
    'defaultTheme': (None, None, None),
    'defaultScopes': ('DefaultScopesParser', None, ['scope']),
    'reservedScopes': ('ReservedScopesParser', None, ['scope']),
    'deviceProfileCheckConfig': ('DeviceProfileCheckConfigParser', None, ['enabled']),
    'directAccessConfig': ('DirectAccessConfigParser', None, ['enabled', 'userIdState', 'scopes', 'allowIps']),
    'logoutUris': ('LogoutUrisParser', None, ['uri']),
    'preferenceOptins': ('PreferenceOptinsParser', None, ['optin']),
    'externalStyleSheets': ('ExternalStyleSheetsParser', None, ['source']),
    'ipWhitelists': ('IpWhitelistsParser', None, ['ip']),
    'secretExpireBy': ('SecretExpireByParser', None, None),
    'psnTicketExpirationCheckDisabled': ('PsnTicketExpirationCheckDisabledParser', None, None),
    'pointOfContacts': (None, None, None),
    'upgradeNeededCheckConfig': ('UpgradeNeededCheckConfigParser', None, ['enabled']),
    'exchangeConfig': ('ExchangeConfigParser', None, ['trustedClients']),
    'legalDocCheckConfig': ('LegalDocCheckConfigParser', None, ['enabled', 'gameIdentifier']),
    'linkingStatusCheckConfig': ('LinkingStatusCheckConfigParser', None, ['enabled']),
    'passwordConfig': ('PasswordConfigParser', ['allowedGrantTypes'], ['userIPHeaderEnabled'])
}